# Generated by Django 4.2.1 on 2023-06-03 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Tytuł')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cena')),
                ('date_from', models.DateField(verbose_name='Data od')),
#                ('date_to', models.DateField(verbose_name='Data do')),
                ('description', models.TextField(blank=True, default='', verbose_name='Opis')),
#                ('status', models.CharField(choices=[('d', 'Dostępna'), ('n', 'Niedostępna')], default='d', max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fuel/', verbose_name='Obraz')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuel.category')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Oferty',
            },
        ),
    ]
