# Generated by Django 4.2.1 on 2023-06-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_alter_fuel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Miasto/stacja'),
        ),
    ]
